### ISSUE TITLE
softDelete "Cannot read property 'hasOwnProperty' of undefined"

### ISSUE THREAD

**Issue by osenvosem** [feathersjs/feathers-hooks-common#48]
### Module version
node 7.1.0
```
  "dependencies": {
    "feathers": "^2.0.2",
    "feathers-hooks": "^1.6.1",
    "feathers-hooks-common": "^2.0.1",
    "feathers-rest": "^1.5.2"
  }

```

### The code
```
const feathers = require('feathers');
const rest = require('feathers-rest');
const hooks = require('feathers-hooks');
const commonHooks = require('feathers-hooks-common');

const app = feathers()
  .configure(rest())
  .configure(hooks());

const data = [{
  text: 'one'
}, {
  text: 'two',
  deleted: true
}];

const messageService = app.service('/messages', {
  find(params) {
    return Promise.resolve(data);
  }
});

messageService.before({
  find: commonHooks.softDelete()
});

app.listen(3000);

```

### The error
```
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at /Volumes/Data/development/dev/two/node_modules/feathers-hooks-common/lib/utils.js:49:16
    at Array.reduce (native)
    at setByDot (/Volumes/Data/development/dev/two/node_modules/feathers-hooks-common/lib/utils.js:47:16)
    at Object.<anonymous> (/Volumes/Data/development/dev/two/node_modules/feathers-hooks-common/lib/new.js:31:27)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by eddyystop** [comment]
softDelete rewritten with tests in v2.0.2
